version: 2
archives:
- files:
  - README.md
  - CHANGELOG.md
  - LICENSE-BlueOak.md
  - LICENSE-MIT.md
  builds:
  - redact
  - redact-ext-azure
  format: tgz
  format_overrides:
  - goos: windows
    format: zip
  name_template: "{{.ProjectName}}-{{.Os}}-{{.Arch}}-{{.Version}}"
builds:
- id: redact
  env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X main.version={{.Version}}
  main: ./cmd/redact
  targets:
  - darwin_arm64
  - darwin_amd64
  - linux_amd64
  - windows_amd64
- id: redact-ext-azure
  binary: redact-ext-azure
  main: ./cmd/redact-ext-azure
  env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X main.version={{.Version}}
  targets:
  - darwin_arm64
  - darwin_amd64
  - linux_amd64
  - windows_amd64
checksum:
  name_template: 'SHA256SUMS.{{.ProjectName}}-{{.Version}}'
project_name: redact
release:
  github:
    name: redact
    owner: julian7
snapshot:
  version_template: "{{ .Tag }}-{{ .ShortCommit }}"
universal_binaries:
- id: redact
  replace: true
- id: redact-ext-azure
  name_template: "redact-ext-azure"
  replace: true
