[tools]
grype = "latest"
"golangci-lint" = "latest"
goreleaser = "latest"
"github:julian7/ihd" = "v0.2.1"

[tasks.build]
description = "Build the tools (default task)"
alias = "default"
quiet = true
run = """
    ver=$(ihd next)
    go build -ldflags="-X main.version=$ver" ./cmd/redact
    go build -ldflags="-X main.version=$ver" ./cmd/redact-ext-aws
    go build -ldflags="-X main.version=$ver" ./cmd/redact-ext-azure
"""

[tasks.check]
description = "Run checks"
run = [
    "go test ./...",
    "golangci-lint run ./...",
    "grype file:go.mod",
]

[tasks.release]
description = "Release version"
run = "goreleaser release --clean"
