[tools]
grype = "latest"
"golangci-lint" = "latest"
goreleaser = "latest"

[tasks.build]
description = "Build the tools (default task)"
alias = "default"
run = [
    "go build ./cmd/redact",
    "go build ./cmd/redact-ext-aws",
    "go build ./cmd/redact-ext-azure",
]

[tasks.check]
description = "Run checks"
run = [
    "go test ./...",
    "golangci-lint run ./...",
    "grype file:go.mod",
]

[tasks.release]
description = "Release version"
run = "goreleaser release --clean"
